version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: 'football'
      POSTGRES_USER: 'kingjinyong'
      POSTGRES_PASSWORD: 'kingjinyong'
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/football'
      SPRING_DATASOURCE_USERNAME: kingjinyong
      SPRING_DATASOURCE_PASSWORD: kingjinyong
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - db

volumes:
  postgres_data:
